### ISSUE TITLE
Random InvalidOperationException (object already attached to graph) when running dot net core unit tests in parallel

### ISSUE THREAD

**Issue by ThisNetWorks** [AutoMapper/AutoMapper.Collection#120]
When running unit tests in parallel (i.e. multithreaded) I am experiencing random InvalidOperationExceptions (object is already in ChangeTracker) when mapping multiple nested lists of dto's back to entities.

From debugging it down it looks like the static Map method in EquivalentExpressionAddRemoveCollectionMapper is experiencing multiple reentry and I think either the destList or items (line 26 & 28) may be getting overwritten during multiple Mapper.Map calls causing destination.add on line 49 to be called on a list which is actually identical.

I've been using Object.ReferenceEquals after the IMapper.Map call to check equality and randomly they are not equal, though I've confirmed that the nested lists all have the same number of items with the same equality on the equality comparison expression.

I am creating a new IMapper object for each of the test classes, rather than using a static mapper and haven't experienced the issue #49 

Running without parallel tests doesn't create the same issue, however it feels like AM.Collections should be able to support multi threading
 
I suspect the static map method may need to be an object reference rather than a static method to prevent however I'm unsure as to the impact that would have elsewhere.

Happy to provide a sample test project if that would help.

**Comment by Tasteful** [comment]
I'm pretty sure that the static `EquivalentExpressionAddRemoveCollectionMapper.Map`-method during multiple executions not is replacing objects between the different executions. The #49 is already solved so that should not be a problem.

The `InvalidOperationExceptions` is thrown by EF and not AM.Collection and without knowing how you setup the data model, mapping and also how the test is written make it hard to guess what the issue can be. Can you make a [gist](https://help.github.com/articles/creating-gists/) that reproduces the problem for us?

**Comment by ThisNetWorks** [comment]
I've forked the repo and created a set of test cases that is able to reproduce the problem.

That being said it requires three test classes to be run in parallel (with a lot of test classes in each) in order to cause the issue, a simple loop of Task.Run( => multiple times) doesn't cause a problem.
So I'm uncertain if this is really an AM problem or a parallel test weirdness, as it has been impossible to reproduce without running tests in parallel

The nested test classes roughly reproduce the schema I use, so kept them similar in case the issue was related to my schema / mapping creation.

Fork is on https://github.com/ThisNetWorks/AutoMapper.Collection/tree/%23120-thread-issue

The invalid operation exception in my actual project is being thrown because new objects are being created when they shouldn't be (should be mapped across to same object). 

For the test project I've just used Object.ReferenceEquals and an assert on that, which randomly fails.

**Comment by ThisNetWorks** [comment]
Oh, also worth noting, I was expecting that if I ran those tests in debug mode and put a breakpoint on line 49 of the EquivalentExpressionAddRemoveCollectionMapper that it would get hit if this was related to static methods, however even with failing tests, the breakpoint is never hit.

**Comment by Tasteful** [comment]
What I can see in the test is that you are mapping a list of item into another list and not an object into an object.

When working with AM you need to map 2 objects to each other to get the equality comparison to work. 

If you create an holder for the objects that you are mapping, like the following and map the holder instead of the collection. Will that result in the same issue?
```
public class ThingHolder
{
    public List<Thing> Items { get; set; }
}
public class ThingDtoHolder
{
    public List<ThingDto> Items { get; set; }
}
```

**Comment by ThisNetWorks** [comment]
Yes, the original code from my project used a holder exactly as you describe above.

Actually the only reason these tests started out mapping a list to a list was because one of the existing tests I started with does that -> Should_Keep_Existing_List

I've just refactored the tests to confirm that the issue exists when using a holder and yes it still occurs (randomly).

Also tried disabling the ForMember maps as I had wondered if being explicit there might have caused problems, but no, same assert fails

**Comment by Tasteful** [comment]
This is most probably an concurrency bug for the setup. The registration of all the `EquivalentExpression` is made into a static field. When running your test as you describe with also the configuration in parallel the registration of the `EquivalentExpression` can go into wrong `IMapper`-configuration.

I have some ideas but they need changes in `AutoMapper` to get that more extensible. It is a bigger process that will take more time.

For the time, turn off the parallel execution.

**Comment by ThisNetWorks** [comment]
I suspected it to be related to one of the static fields. For the app in question I've moved the problematic threaded issues into AfterMap mapping expressions, and handled the lists manually.

I guess the concern (for me) was less around parallel test execution, and more about what could happen in the wild as api recieves a lot of traffic.

Cheers

**Comment by Tasteful** [comment]
Yes, it is related to the static fields that are used to keep the `EquivalentExpression`s in. To be able to make it 100% threadsafe for the initialization the storage of the `EquivalentExpression` need to be changed and should probably be stored somehow inside in AM.IConfigurationProvider.
